apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: oukchiren/myapp:f95f4b40401706163cc3f38b7bbdd3343a5a70ff
        ports:
        - containerPort: 3000