apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-health-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saas-health-frontend
  template:
    metadata:
      labels:
        app: saas-health-frontend
    spec:
      containers:
      - name: saas-health-frontend
        image: oukchiren/myapp:f95f4b40401706163cc3f38b7bbdd3343a5a70ff
        ports:
        - containerPort: 3000